
services:
  # Base de données MySQL
  mysql-gestion-etudiants:
    image: mysql:8.0
    container_name: mysql-gestion-etudiants
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_etudiants
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - backend-network
    volumes:
      - mysql-data:/var/lib/mysql

  # Backend Spring Boot
  gestion-etudiants-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestion-etudiants-api
    restart: always
    depends_on:
      - mysql-gestion-etudiants
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-gestion-etudiants:3306/gestion_etudiants?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - backend-network

  # Frontend Vue.js
  frontend-gestion-etudiants:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-gestion-etudiants
    restart: always
    depends_on:
      - gestion-etudiants-api
    ports:
      - "5173:5173"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mysql-data:
