version: "3.8"

services:
  # Service MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql-gestion-etudiants
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_etudiants
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - backend-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      interval: 10s
      retries: 5
      timeout: 5s

  # Service Backend (Spring Boot API)
  api:
    build: .
    container_name: gestion-etudiants-api
    depends_on:
      mysql:
        condition: service_healthy  # Attend que MySQL soit prêt avant de démarrer
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gestion_etudiants?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - backend-network

  # Service Frontend (Vue.js)
  frontend:
    build: ./frontend
    container_name: gestion-etudiants-frontend
    depends_on:
      - api
    environment:
      VUE_APP_BACKEND_URL: http://gestion-etudiants-api:8080  # Assure la bonne communication
    ports:
      - "5173:5173"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mysql-data:
