openapi: 3.0.0
info:
  title: API Étudiants
  description: API pour la gestion des étudiants
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Serveur de développement

paths:
  /students:
    get:
      summary: Récupérer tous les étudiants
      responses:
        '200':
          description: Liste des étudiants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'

    post:
      summary: Ajouter un nouvel étudiant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '201':
          description: Étudiant ajouté avec succès

  /students/{id}:
    get:
      summary: Récupérer un étudiant par ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Étudiant trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '404':
          description: Étudiant non trouvé

components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        age:
          type: integer
      required:
        - name
        - age
